name: Functional Boredom
favicon: null
layout_spectrum: 0.926584233995527
typography_spectrum: 0.24928393145091832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8244658892508596
  lightness: 0.13449268112890422
  saturation: 0.09896232839673758
  rhythmicContrast: 0.1640518878120929
purpose: []
