name: Functional Boredom
favicon: null
layout_spectrum: 0.26549
typography_spectrum: 0.56387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8244658892508596
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
